use_frameworks!

target 'BaasJustTest_Example' do
  pod 'BaasJustTest', :path => '../'

  target 'BaasJustTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
